# Generated by Django 2.2.3 on 2019-09-11 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRTLOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendToWallet', models.CharField(max_length=100)),
                ('amountInTRTL', models.FloatField()),
                ('amountInUSD', models.FloatField()),
                ('nickname', models.CharField(max_length=100)),
                ('orderTime', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
