# Generated by Django 2.2.3 on 2019-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtlecoinWallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trtlorder',
            name='orderTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
