# Generated by Django 2.2.3 on 2019-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtlecoinWallet', '0002_auto_20190913_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='trtlorder',
            name='paymentstatus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
