# Generated by Django 2.2.3 on 2019-09-13 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('turtlecoinWallet', '0003_trtlorder_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trtlorder',
            name='id',
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='inovice',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='orderid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='transaction',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
