# Generated by Django 2.2.3 on 2019-09-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turtlecoinWallet', '0004_auto_20190914_0325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TRTLOrder',
        ),
    ]
