# Generated by Django 2.2.3 on 2019-09-14 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRTLOrder',
            fields=[
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sendToWallet', models.CharField(max_length=100)),
                ('amountInTRTL', models.FloatField()),
                ('amountInUSD', models.FloatField()),
                ('nickname', models.CharField(max_length=100)),
                ('orderTime', models.TimeField(auto_now_add=True)),
                ('paymentstatus', models.CharField(max_length=100)),
                ('inovice', models.CharField(max_length=100)),
                ('transaction', models.CharField(max_length=100)),
            ],
        ),
    ]
