# Generated by Django 2.2.3 on 2019-09-14 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trtlorder',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='trtlorder',
            name='inovice',
        ),
        migrations.RemoveField(
            model_name='trtlorder',
            name='orderTime',
        ),
        migrations.RemoveField(
            model_name='trtlorder',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='trtlorder',
            name='paymentstatus',
        ),
        migrations.RemoveField(
            model_name='trtlorder',
            name='transaction',
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trtlorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
