# Generated by Django 2.2.3 on 2019-09-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190915_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trtlorder',
            name='tx',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
